### ISSUE TITLE
Error while compiling in arwen/context/arwen.go

### ISSUE THREAD

**Issue by BlockchainRevolutionOnline** [ElrondNetwork/arwen-wasm-vm#21]
There is probably something wrong in arwen.go:

`arwen-wasm-vm/cmd/test$ go build

\# github.com/ElrondNetwork/arwen-wasm-vm/arwen/context
../../arwen/context/arwen.go:189:101: cannot use "uniform_one" (type string) as type *[410]uint32 in argument to wasmer.NewMeteredInstanceWithImports
`

Or I don't know how to build arwen-wasm-vm. Please add howto build it in README.md.Thanks Florian

**Comment by sasurobert** [comment]
Hey. It was fixed a few minutes ago. Please take the lastest update from master.

**Comment by BlockchainRevolutionOnline** [comment]
Hey Robert, 
please explain how to build and how to use this code. 
Thanks!
Florian

**Comment by sasurobert** [comment]
Hey Florian. This code is hard to use alone. This is used together with Elrond-Node, or Elrond-Debug-Node in order to deploy and execute smart contracts.
